# Load in numpy (remember to pip install numpy first) [!pip install numpy]

In [6]:
import numpy as np

# Basics

In [66]:
# initialize array 

a = np.array([1,2,3], dtype='int32') # 1d array
print(a)


[1 2 3]


In [92]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]], dtype='int16')  #2d arrays

print(b)

# for i in b:
#     for j in i:
#         print(j, end=" ")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [106]:
# Get dimension (use .ndim)

print(f"The dimension in a is {a.ndim}")
print(f"The dimension in b is {b.ndim}")

The dimension in a is 1
The dimension in b is 2


In [104]:
# Get Shape

print(a.shape)
print(b.shape)

(3,)
(5, 3)


In [102]:
#  Get Type

print(a.dtype)
print(b.dtype)

int32
int16


In [100]:
# Get Size
print(a.itemsize)
print(b.itemsize)

4
2


In [96]:
# Get the total elements

print(a.size)
print(b.size)

3
15


In [94]:
# Get total size

print(a.nbytes)
print(b.nbytes)

12
30


# Accessing/Changing specific elements, rows, columns, etc

In [115]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(a)
print(f"\nShape of a is : {a.shape}")

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

Shape of a is : (2, 7)


In [139]:
# Get a specific element [row, col]
print(a[1,2])

10


In [229]:
# get a specific row [row, col]
# we can also include the indexing operator (slicing) [startindex : ending/stopindex : stepsize] 

print(a[0,:]) # first row
print(a[1,:]) # second row

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [859]:
# get specific columns [row, col]
# we can also include the indexing operator (slicing) [start : stop : stepsize]

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b = np.array([2,4,6,8,10,12,14])

print(a[:,4])
print(a[:,2:5:2])
print(a[:,1::2])

print(b[::2])


[ 5 12]

[[ 3  5]
 [10 12]]

[[ 2  4  6]
 [ 9 11 13]]

[ 2  6 10 14]


In [885]:
# modify the values in the arrays

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b = np.array([2,4,6,8,10,12,14])

# a[0,0] = 2
# b[3] = 9

a[:,1::2] = 1,2,3
b[1::2] = [num * 2 for num in b[1::2]]

print(a)
print(b)



[ 8 16 24]
[[ 1  1  3  2  5  3  7]
 [ 8  1 10  2 12  3 14]]
[ 2  8  6 16 10 24 14]


# 3d arrays

In [1020]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)




[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [1166]:
# get specific element (work outside in)
# print(b[0,1,0])

print(b[0,1,1])

4


In [1168]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b[:,1,:])

[[9 9]
 [8 8]]


# Initializing diffrent types of arrays

In [1180]:
# ALl 0s matrix
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [1206]:
# ALl 1s matrix
print(np.ones((3,3),dtype='int32'))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [1204]:
# Any other number
print(np.full((2,2),99,dtype='float32'))

[[99. 99.]
 [99. 99.]]


In [1222]:
# Any other number (full_like)

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(np.full_like(a,9))


(2, 7)
[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [1226]:
# Random decimal numbers

print(np.random.rand(4,2))
print()
print(np.random.random_sample(a.shape))

[[0.93720297 0.90589932]
 [0.25744926 0.24975968]
 [0.63690475 0.86662843]
 [0.86457746 0.53877311]]

[[0.89858493 0.9352953  0.4026453  0.47715608 0.06251584 0.56903946
  0.16406802]
 [0.54653792 0.6013955  0.4558922  0.34182383 0.59071489 0.85497001
  0.21330332]]


In [1290]:
# Random int values
np.random.randint(1,6,size=(3,3))

array([[-1,  1, -2],
       [ 3,  4,  1],
       [ 0,  5, -1]])

In [1306]:
# The identity matric
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [1338]:
# repeat an array
arr = np.array([[1,2,3,4,5]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [1444]:

o = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

o[1:-1,1:-1] = z

print(o)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!