# Load in numpy (remember to pip install numpy first) [!pip install numpy]

In [3]:
import numpy as np

# Basics

In [16]:
# initialize array 

a = np.array([1,2,3]) # 1d array
print(a)


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [18]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])  #2d arrays

print(b)

# for i in b:
#     for j in i:
#         print(j, end=" ")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


# To get the dimensions (.ndim)

In [32]:
# Get dimension (use .ndim)

print(f"The dimension in a is {a.ndim}")
print(f"The dimension in b is {b.ndim}")

The dimension in a is 1
The dimension in b is 2
